# Generated by Django 5.2.6 on 2025-09-08 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nilai_mtk', models.FloatField()),
                ('nilai_bindo', models.FloatField()),
                ('nilai_bing', models.FloatField()),
                ('nilai_ipa', models.FloatField()),
                ('minat', models.CharField(max_length=40)),
                ('jurusan', models.CharField(choices=[('AKUNTANSI', 'Akuntansi & Keuangan Lembaga'), ('PERKANTORAN', 'Manajemen Perkantoran & Layanan Bisnis')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('nilai_mtk', models.FloatField(default=0)),
                ('nilai_bindo', models.FloatField(default=0)),
                ('nilai_bing', models.FloatField(default=0)),
                ('nilai_ipa', models.FloatField(default=0)),
                ('minat', models.CharField(choices=[('Administrasi', 'Administrasi'), ('Berhitung', 'Berhitung'), ('Teknologi', 'Teknologi'), ('Bahasa', 'Bahasa')], default='Administrasi', max_length=40)),
                ('jurusan', models.CharField(blank=True, choices=[('AKUNTANSI', 'Akuntansi & Keuangan Lembaga'), ('PERKANTORAN', 'Manajemen Perkantoran & Layanan Bisnis')], max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan_prediksi', models.CharField(choices=[('AKUNTANSI', 'Akuntansi & Keuangan Lembaga'), ('PERKANTORAN', 'Manajemen Perkantoran & Layanan Bisnis')], max_length=20)),
                ('probability', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.student')),
            ],
        ),
    ]
