# Generated by Django 5.2.6 on 2025-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0002_alter_student_nis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minat',
            field=models.CharField(choices=[('Administrasi', 'Administrasi'), ('Komunikasi', 'Komunikasi'), ('Korespodensi', 'Korespodensi'), ('Berhitung', 'Berhitung'), ('Analisis Data', 'Analisis Data'), ('Keuangan', 'Keuangan')], default='Administrasi', max_length=40),
        ),
    ]
